# Generated by Django 2.0.13 on 2020-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200624_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='externalTax',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
