# Generated by Django 2.0.13 on 2020-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200624_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='externalTax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
