# Generated by Django 2.0.13 on 2020-06-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200624_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
